# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61e8a13ca13b018ce5c487f13adbc5dafa44eca717bfc43fada9489da3afa519ea18107d8847b760cfcef462c2502dcbb72f2f4e9bce5a0bbe271aaab4fbdcac

test:
  secret_key_base: cd11ee306adf9b562e2322c356b8cc4a2bca79bcd5e9e10638b60fcf0d2c62ea1ccceec2809fe2eddc9a2fff61411860d55ab3312e51d9939e7743efa7602cf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


test
